[project]
name = "blog"
version = "0.1.0"
description = "Das Bityard - Ze Blog"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pelican[markdown]>=4.11.0",
]

[project.urls]
Homepage = "https://blog.bityard.net"
Repository = "https://github.com/cu/blog"
