name: deploy to CF pages
on:
  push:
    paths-ignore:
      - .gitignore
      - Makefile
      - README.md
jobs:
  deploy:
    name: generate HTML
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Generate HTML
        run: make publish

      - name: Push to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: blog
          directory: output
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
